import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/layout/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hedera Dapp",
  description: "Generated by create next app",
  icons: "hedera.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
<body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <NavBar/>
          <div className="pt-24 h-screen">
            {children}
          </div>
          <footer className="absolute bottom-0 w-full flex flex-col items-center justify-center p-4 text-sm text-gray-500 bg-gray-900">
            <p>© {new Date().getFullYear()} MichiMint - Built with ❤️ for the Hedera Ecosystem</p>
            <p>
              Open-source under the{" "}
              <a href="https://opensource.org/licenses/MIT" className="underline hover:text-gray-300">
                MIT License
              </a>
            </p>
            <p>
              Developed by{" "}
              <a href="https://github.com/Maximiliano-Santana" className="underline hover:text-gray-300">
                Maximiliano
              </a>
            </p>
          </footer>
      </body>
    </html>
  );
}
